### ISSUE TITLE
Vapor Crash on Launch

### ISSUE THREAD

**Issue by awais-shahid** [syedqamara/HelloServerSideSwift#2]
> 2019-04-25 17:28:50.198266+0500 Run[58259:2461512] Fatal error: Error raised at top level: bind(descriptor:ptr:bytes:) failed: Address already in use (errno: 48): file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1001.8.63.13/swift/stdlib/public/core/ErrorType.swift, line 200

**Comment by syedqamara** [comment]
List down all process with this command.

```sudo lsof -i :8080```

Now Kill Each Process by bellow Command.

```kill {PID of the process}```
