### ISSUE TITLE
Vapor update stuck on loading

### ISSUE THREAD

**Issue by UmairSharif** [syedqamara/HelloServerSideSwift#3]
While running a command "vapor update" my terminal stuck in loading and nothing happens.

**Comment by syedqamara** [comment]
> While running a command "vapor update" my terminal stuck in loading and nothing happens.

Check your `Package.swift` file you might have entered a package which is already being install from another package as nested dependency.

For Example.
You are entering a package with name `ABC` And there is another package named `XYZ` which is further dependent on `ABC` so `ABC` cannot be installed twice. So remove the line for installing `ABC` and then `vapor build`
